import { env, AutoModel, RawImage, Tensor } from "https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.2.0";

const ID = "depth-anything-v3-small";
const REPO = "onnx-community/depth-anything-v3-small";
const REV = "0b6a7f3bf5595f9950b91389e0da3a0de130324c";
const PRECISIONS = { fp32: { weightsSize: 105343155, size: 105343284, modelKeys: ["model.onnx", "model.onnx_data"], dtype: "fp32", candidateDevices: ["wasm", "webgpu"] } };
const SUPPORTED = { fp32: { ...PRECISIONS.fp32, supportedDevices: ["wasm", "webgpu"] } };
const MANIFEST = {
  contractVersion: "1.0",
  model: { id: ID, displayName: "Depth Anything V3 Small", provider: "ByteDance Seed", providerUrl: "https://github.com/ByteDance-Seed/depth-anything-3", license: "Apache-2.0", licenseUrl: "https://www.apache.org/licenses/LICENSE-2.0.txt", lastUpdated: "2025-11-13T18:44:51.000Z", sourceRepository: "depth-anything/DA3-SMALL", repository: REPO, artifactRevision: REV, artifactLastUpdated: "2025-11-15T00:18:15.000Z", task: "depth-estimation", description: "A compact monocular geometry model that estimates relative per-pixel depth from one browser image and returns a visual depth map plus numeric summary data.", intendedUses: ["Visualizing relative scene depth.", "Prototyping browser spatial effects and depth-aware image processing."], limitations: ["Depth is relative rather than a calibrated metric distance.", "Thin structures, reflective or transparent surfaces, low light, blur, and unfamiliar visual domains may produce incorrect geometry.", "The single-image worker does not expose the source model's multi-view pose workflow.", "Depth estimates must not be used as the sole input for navigation, robotics, accessibility, or other safety-critical decisions."] },
  runtime: { engine: { name: "Transformers.js", version: "4.2.0" }, precisions: SUPPORTED },
  input: { description: "Exactly one browser-readable image blob URL.", alternatives: [{ name: "image_blob_url", type: "string(blob URL)", required: true }] },
  config: { model: [], generation: [] },
  output: { description: "A grayscale depth-map blob URL and finite numeric depth statistics.", fields: [{ name: "depth_blob_url", type: "string(blob URL)", required: true }, { name: "width", type: "integer", required: true }, { name: "height", type: "integer", required: true }, { name: "statistics", type: "{min,max,mean}", required: true }, { name: "signature", type: "number[]", required: true }], example: { depth_blob_url: "blob:…", width: 518, height: 350, statistics: { min: 0, max: 255, mean: 127 }, signature: [0.2, 0.8] } },
  operations: ["checkModelSupports", "init", "download", "generate", "clearMemory"],
  benchmark: { report: "benchmarks/depth-anything-v3-small.json", testedAt: "2026-09-12T10:18:02.005Z", fixture: { file: "modnet-portrait-pexels-5965592.jpg", url: "https://f005.backblazeb2.com/file/hubters-webai-public/assets/benchmarks/modnet-portrait-pexels-5965592.jpg", size: 78124, sha1: "38212739a4a4f0be25d84863cf991d7fb6c6d818", width: 1024, height: 683, license: "Pexels License", licenseUrl: "https://www.pexels.com/license/", expected: { file: "depth-anything-v3-small.json", size: 727, sha1: "bc7d37b8da85772a0ffb158f3c84fdcd3d8af2e7" } }, candidates: PRECISIONS, qualityGate: "Finite non-flat depth map whose 8×8 normalized signature remains within the checked-in reference tolerance.", invalidatedBy: ["artifact revision change", "runtime version change", "fixture or quality-gate change", "browser/backend behavior change"], results: [{ precision: "fp32", device: "wasm", status: "pass", runtime: { loadMs: 14119.1, inferenceMs: 4820.6, imagesPerSecond: 0.2074, grade: "slow" }, quality: { signatureMeanAbsoluteError: 0 } }, { precision: "fp32", device: "webgpu", status: "pass", runtime: { loadMs: 12408.1, inferenceMs: 200.8, imagesPerSecond: 4.9801, grade: "excellent" }, quality: { signatureMeanAbsoluteError: 0 } }] },
};

const state = { initializing: false, initialized: false, generating: false };
let estimator = null, outputUrl = null;
const send = (requestId, type, data) => self.postMessage({ requestId, type, data });
const caps = { supportedModes: ["webai"], supportedPrecisions: Object.keys(SUPPORTED), supportedPrecisionsDevicesMap: SUPPORTED, doesSupportStreamGeneration: false, externalInterrupt: true, workerVersion: "v4", transformersJsVersion: "4.2.0", cacheModelId: REPO };
function configure(c = {}) { env.allowRemoteModels = c.allowRemoteModels ?? true; env.allowLocalModels = c.allowLocalModels ?? false; env.useBrowserCache = c.useBrowserCache ?? true; if (c.remoteHost) env.remoteHost = c.remoteHost; if (c.remotePathTemplate) env.remotePathTemplate = c.remotePathTemplate; if (c.localModelPath) env.localModelPath = c.localModelPath; }
function validateInit(data) { const precision = data?.precision, device = data?.device, s = SUPPORTED[precision]; if (!s) throw Error(`Unsupported precision: ${precision}`); if (!s.supportedDevices.includes(device)) throw Error(`Precision ${precision} is only supported on: ${s.supportedDevices.join(", ")}`); if (device === "webgpu" && !self.navigator?.gpu) throw Error("WebGPU is unavailable"); return { precision, device }; }
async function clear() { if (estimator?.dispose) await estimator.dispose(); estimator = null; if (outputUrl) URL.revokeObjectURL(outputUrl); outputUrl = null; state.initialized = false; }
async function load(data, requestId) { const { precision, device } = validateInit(data); await clear(); estimator = await AutoModel.from_pretrained(REPO, { revision: REV, dtype: precision, device, progress_callback: value => send(requestId, "downloadProgress", value) }); }
function signatureFrom(data, width, height) { const values = []; for (let gy = 0; gy < 8; gy++) for (let gx = 0; gx < 8; gx++) { const x = Math.min(width - 1, Math.round((gx + 0.5) * width / 8)); const y = Math.min(height - 1, Math.round((gy + 0.5) * height / 8)); values.push(Number((data[(y * width + x) * (data.length === width * height ? 1 : data.length / (width * height))] / 255).toFixed(6))); } return values; }
async function preprocess(url) { const source = await RawImage.read(url), scale = 504 / Math.min(source.width, source.height), width = Math.max(14, Math.round(source.width * scale / 14) * 14), height = Math.max(14, Math.round(source.height * scale / 14) * 14), image = await source.resize(width, height), plane = width * height, values = new Float32Array(3 * plane), mean = [0.485, 0.456, 0.406], std = [0.229, 0.224, 0.225]; for (let i = 0; i < plane; i++) for (let c = 0; c < 3; c++) values[c * plane + i] = (image.data[i * image.channels + c] / 255 - mean[c]) / std[c]; return { tensor: new Tensor("float32", values, [1, 1, 3, height, width]), width, height }; }
async function generate(data) { const image = data?.userInput?.image_blob_url; if (typeof image !== "string" || !image.startsWith("blob:")) throw Error("userInput.image_blob_url must be a valid blob URL"); const prepared = await preprocess(image), output = await estimator({ pixel_values: prepared.tensor }), predicted = output?.predicted_depth; if (!predicted?.data?.length) throw Error("Model returned no predicted_depth tensor"); const values = predicted.data; let min = Infinity, max = -Infinity, sum = 0; for (const value of values) { if (!Number.isFinite(value)) throw Error("Model returned non-finite depth values"); if (value < min) min = value; if (value > max) max = value; sum += value; } const mean = sum / values.length, span = max - min; if (!(span > 0)) throw Error("Model returned a flat depth map"); const gray = new Uint8ClampedArray(values.length); for (let i = 0; i < values.length; i++) gray[i] = Math.round((values[i] - min) / span * 255); const canvas = new OffscreenCanvas(prepared.width, prepared.height), context = canvas.getContext("2d"), rgba = new Uint8ClampedArray(values.length * 4); for (let i = 0; i < gray.length; i++) { rgba[i * 4] = rgba[i * 4 + 1] = rgba[i * 4 + 2] = gray[i]; rgba[i * 4 + 3] = 255; } context.putImageData(new ImageData(rgba, prepared.width, prepared.height), 0, 0); if (outputUrl) URL.revokeObjectURL(outputUrl); outputUrl = URL.createObjectURL(await canvas.convertToBlob({ type: "image/png" })); return { depth_blob_url: outputUrl, width: prepared.width, height: prepared.height, statistics: { min, max, mean }, signature: signatureFrom(gray, prepared.width, prepared.height) }; }
self.addEventListener("message", async ({ data: { requestId, type, data } = {} }) => { try { if (type === "checkModelSupports") { configure(data?.workerConfig); send(requestId, type, { ...caps, manifest: MANIFEST }); return; } if (type === "download") { const s = SUPPORTED[data?.precision]; if (!s) throw Error(`Unsupported precision: ${data?.precision}`); await load({ ...data, device: "wasm" }, requestId); await clear(); send(requestId, type, { status: "success" }); return; } if (type === "init") { if (state.initializing || state.generating) throw Error("Worker is busy"); state.initializing = true; try { await load(data, requestId); state.initialized = true; send(requestId, type, { status: "success" }); } finally { state.initializing = false; } return; } if (type === "generate") { if (!state.initialized || !estimator) throw Error("Call init before generate"); if (state.generating) throw Error("Generation already in progress"); state.generating = true; try { send(requestId, "generated", { status: "success", result: await generate(data) }); } finally { state.generating = false; } return; } if (type === "generateStream") throw Error("Stream generation is not supported for depth estimation"); if (type === "clearMemory") { await clear(); send(requestId, type, { status: "success" }); return; } throw Error(`Unknown operation: ${type}`); } catch (error) { send(requestId, "error", { message: error instanceof Error ? error.message : String(error), context: type }); } });
self.postMessage({ type: "worker initialized", data: { success: true, workerVersion: "v4", modelId: ID } });
