import { env, AutoTokenizer, AutoModelForCausalLM, TextStreamer } from "https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.2.0";
const ID="qwen3.5-0.8b", REPO="onnx-community/Qwen3.5-0.8B-Text-ONNX", REV="1e45daba048899e7f771657ada617ec49350aa91";
const PRECISIONS={q4f16:{weightsSize:469929410,size:489174504,modelKeys:["model_q4f16.onnx","model_q4f16.onnx_data"],dtype:"q4f16",candidateDevices:["wasm","webgpu"]},q4:{weightsSize:551247327,size:570492421,modelKeys:["model_q4.onnx","model_q4.onnx_data"],dtype:"q4",candidateDevices:["wasm","webgpu"]},q8:{weightsSize:938947493,size:958192587,modelKeys:["model_quantized.onnx","model_quantized.onnx_data"],dtype:"q8",candidateDevices:["wasm","webgpu"]},fp16:{weightsSize:1538945869,size:1558190963,modelKeys:["model_fp16.onnx","model_fp16.onnx_data"],dtype:"fp16",candidateDevices:["wasm","webgpu"]},fp32:{weightsSize:3077060202,size:3096305296,modelKeys:["model.onnx","model.onnx_data","model.onnx_data_1"],dtype:"fp32",candidateDevices:["wasm","webgpu"]}};
const SUPPORTED={q4f16:{supportedDevices:["webgpu"],...PRECISIONS.q4f16},q4:{supportedDevices:["webgpu"],...PRECISIONS.q4},q8:{supportedDevices:["webgpu"],...PRECISIONS.q8},fp16:{supportedDevices:["webgpu"],...PRECISIONS.fp16},fp32:{supportedDevices:["webgpu"],...PRECISIONS.fp32}};
const BENCHMARK_RESULTS=[
{precision:"fp32",device:"wasm",status:"fail",runtime:{loadMs:null,inferenceMs:null,totalMs:197021.8,grade:"failed"},failure:"std::bad_alloc"},
{precision:"fp32",device:"webgpu",status:"pass",runtime:{loadMs:198120.4,inferenceMs:1234.1,totalMs:201453.3,firstChunkMs:1200.6,tokensPerSecond:1.621,grade:"very-slow"},quality:{grade:"exact-match",output:"Paris",nonEmpty:true,nonRepetitive:true}},
{precision:"fp16",device:"wasm",status:"fail",runtime:{loadMs:null,inferenceMs:null,totalMs:124902.4,grade:"failed"},failure:"std::bad_alloc"},
{precision:"fp16",device:"webgpu",status:"pass",runtime:{loadMs:110611.1,inferenceMs:767.2,totalMs:113322,firstChunkMs:739.7,tokensPerSecond:2.607,grade:"very-slow"},quality:{grade:"exact-match",output:"Paris",nonEmpty:true,nonRepetitive:true}},
{precision:"q8",device:"wasm",status:"fail",runtime:{loadMs:null,inferenceMs:null,totalMs:75129.5,grade:"failed"},failure:"missing-GatherBlockQuantized-kernel"},
{precision:"q8",device:"webgpu",status:"pass",runtime:{loadMs:67858,inferenceMs:412.2,totalMs:70546.9,firstChunkMs:399.3,tokensPerSecond:4.852,grade:"slow"},quality:{grade:"exact-match",output:"Paris",nonEmpty:true,nonRepetitive:true}},
{precision:"q4",device:"wasm",status:"fail",runtime:{loadMs:null,inferenceMs:null,totalMs:100653.9,grade:"failed"},failure:"missing-GatherBlockQuantized-kernel"},
{precision:"q4",device:"webgpu",status:"pass",runtime:{loadMs:88126.9,inferenceMs:338.4,totalMs:90527.3,firstChunkMs:325.2,tokensPerSecond:5.91,grade:"slow"},quality:{grade:"exact-match",output:"Paris",nonEmpty:true,nonRepetitive:true}},
{precision:"q4f16",device:"wasm",status:"fail",runtime:{loadMs:null,inferenceMs:null,totalMs:86838.4,grade:"failed"},failure:"missing-GatherBlockQuantized-kernel"},
{precision:"q4f16",device:"webgpu",status:"pass",runtime:{loadMs:89163.2,inferenceMs:337,totalMs:91295.4,firstChunkMs:322,tokensPerSecond:5.935,grade:"slow"},quality:{grade:"exact-match",output:"Paris",nonEmpty:true,nonRepetitive:true}}
];
const MANIFEST={contractVersion:"1.0",model:{id:ID,displayName:"Qwen3.5 0.8B — Text Chat",provider:"Qwen / Alibaba Cloud",providerUrl:"https://qwenlm.github.io/",license:"Apache-2.0",licenseUrl:"https://huggingface.co/Qwen/Qwen3.5-0.8B/blob/main/LICENSE",lastUpdated:"2026-03-02T11:26:58.000Z",sourceRepository:"Qwen/Qwen3.5-0.8B",repository:REPO,artifactRevision:REV,artifactLastUpdated:"2026-04-22T22:29:59.000Z",task:"text-generation",description:"A compact Qwen3.5 text language model for local conversational generation in a browser through Transformers.js and ONNX Runtime Web.",intendedUses:["Local chat, drafting, rewriting, and summarization.","Benchmarking browser LLM inference."],limitations:["Generated text may be incorrect, unsafe, or fabricated and requires review.","The model is small and trades reasoning quality for browser memory and speed.","The tested ONNX artifact may require newer ONNX Runtime Web support."]},runtime:{engine:{name:"Transformers.js",version:"4.2.0"},precisions:SUPPORTED},input:{description:"Chat messages with roles system, user, or assistant.",alternatives:[{name:"messages",type:"Array<{ role: 'system' | 'user' | 'assistant', content: string }>",required:true}]},config:{model:[{name:"max_new_tokens",type:"integer",default:128,minimum:1,maximum:1024},{name:"temperature",type:"number",default:0.7,minimum:0,maximum:2},{name:"do_sample",type:"boolean",default:true}],generation:[]},output:{description:"Generated assistant text and updated messages.",fields:[{name:"result",type:"string"},{name:"messages",type:"array"},{name:"structured_output",type:"boolean"}],example:{result:"Hello!",messages:[],structured_output:false}},operations:["checkModelSupports","init","download","generate","generateStream","clearMemory"],benchmark:{report:"benchmarks/qwen3.5-0.8b.json",testedAt:"2026-09-09T15:07:59.318Z",fixture:{file:"qwen3.5-0.8b.json",url:"https://f005.backblazeb2.com/file/hubters-webai-public/assets/benchmarks/qwen3.5-0.8b.json",size:296,sha1:"842e28ba6ec5218cbc34eb677df214d89064119a"},candidates:PRECISIONS,invalidatedBy:["artifact revision change","runtime version change","fixture or quality gate change","browser/backend change"],results:BENCHMARK_RESULTS}};
const state={initialized:false,initializing:false,generating:false}; let tokenizer=null,model=null;
const caps={supportedModes:["webai"],supportedPrecisions:Object.keys(SUPPORTED),supportedPrecisionsDevicesMap:SUPPORTED,doesSupportStreamGeneration:true,externalInterrupt:true,workerVersion:"v4",transformersJsVersion:"4.2.0",cacheModelId:REPO};
const send=(requestId,type,data)=>self.postMessage({requestId,type,data}); const progress=(id,v)=>send(id,"downloadProgress",v);
function configure(workerConfig={}){env.allowRemoteModels=workerConfig.allowRemoteModels??true;env.allowLocalModels=workerConfig.allowLocalModels??false;env.useBrowserCache=workerConfig.useBrowserCache??true;if(workerConfig.remoteHost)env.remoteHost=workerConfig.remoteHost;if(workerConfig.remotePathTemplate)env.remotePathTemplate=workerConfig.remotePathTemplate;if(workerConfig.localModelPath)env.localModelPath=workerConfig.localModelPath;}
function validate(data){const p=data?.precision,d=data?.device,s=SUPPORTED[p];if(!s)throw Error(`Unsupported precision: ${p}`);if(!s.supportedDevices.includes(d))throw Error(`Precision ${p} is only supported on: ${s.supportedDevices.join(", ")}.`);if(d==="webgpu"&&!self.navigator?.gpu)throw Error("WebGPU is unavailable.");return {p,d};}
function messages(data){const m=data?.userInput?.messages;if(!Array.isArray(m)||!m.length)throw Error("userInput.messages must be a non-empty array.");for(const x of m)if(!x||!["system","user","assistant"].includes(x.role)||typeof x.content!=="string"||!x.content.trim())throw Error("Each message needs a valid role and non-empty content.");if(m.at(-1).role!=="user")throw Error("The final message must be from the user.");return m;}
async function clear(){if(model?.dispose)await model.dispose();model=null;tokenizer=null;state.initialized=false;}
async function load(data,id){const {p,d}=validate(data);await clear();tokenizer=await AutoTokenizer.from_pretrained(REPO,{revision:REV,progress_callback:v=>progress(id,v)});model=await AutoModelForCausalLM.from_pretrained(REPO,{revision:REV,dtype:p,device:d,progress_callback:v=>progress(id,v)});}
async function generate(data,id,streaming){const m=messages(data),cfg={max_new_tokens:128,temperature:.7,do_sample:true,top_k:50,top_p:1,repetition_penalty:1,...data.modelConfig};if(!Number.isInteger(cfg.max_new_tokens)||cfg.max_new_tokens<1||cfg.max_new_tokens>1024)throw Error("max_new_tokens must be 1-1024");if(typeof cfg.do_sample!=="boolean")throw Error("do_sample must be boolean");if(!Number.isFinite(cfg.temperature)||cfg.temperature<0||cfg.temperature>2)throw Error("temperature must be 0-2");if(!Number.isInteger(cfg.top_k)||cfg.top_k<1)throw Error("top_k must be positive");if(!Number.isFinite(cfg.top_p)||cfg.top_p<=0||cfg.top_p>1)throw Error("top_p must be greater than 0 and at most 1");if(!Number.isFinite(cfg.repetition_penalty)||cfg.repetition_penalty<=0)throw Error("repetition_penalty must be positive");const prompt=tokenizer.apply_chat_template(m,{tokenize:false,add_generation_prompt:true});const inputs=await tokenizer(prompt,{add_special_tokens:false});const streamer=streaming?new TextStreamer(tokenizer,{skip_prompt:true,skip_special_tokens:true,callback_function:t=>{if(t)send(id,"streamChunk",{result:t,text:t,structured_output:false});}}):undefined;const out=await model.generate({...inputs,...cfg,pad_token_id:tokenizer.pad_token_id??tokenizer.eos_token_id,streamer});const ids=out.tolist()[0].slice(inputs.input_ids.dims.at(-1));const result=tokenizer.decode(ids,{skip_special_tokens:true});return {result,messages:[...m,{role:"assistant",content:result}],structured_output:false};}
self.addEventListener("message",async({data:{requestId,type,data}={}})=>{try{if(type==="checkModelSupports"){configure(data?.workerConfig);send(requestId,type,{...caps,manifest:MANIFEST});return;}if(type==="download"){if(state.initializing||state.generating)throw Error("Worker is busy");await load(data,requestId);await clear();send(requestId,type,{status:"success"});return;}if(type==="init"){if(state.initializing||state.generating)throw Error("Worker is busy");state.initializing=true;try{await load(data,requestId);state.initialized=true;send(requestId,type,{status:"success"});}finally{state.initializing=false;}return;}if(type==="generate"||type==="generateStream"){if(!state.initialized||!model||!tokenizer)throw Error("Call init before generate");if(state.generating)throw Error("Generation already in progress");state.generating=true;try{send(requestId,"generated",{status:"success",result:await generate(data,requestId,type==="generateStream")});}finally{state.generating=false;}return;}if(type==="clearMemory"){if(state.generating)throw Error("Cannot clear memory while generation is active");await clear();send(requestId,type,{status:"success"});return;}throw Error(`Unknown operation: ${type}`);}catch(e){send(requestId,"error",{message:e instanceof Error?e.message:String(e),context:type});}});
self.postMessage({type:"worker initialized",data:{success:true,workerVersion:"v4",modelId:ID}});
